<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container798Kc8x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container798Kc8x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container798Kc8x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container798Kc8x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container798Kc8x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '798Kc8x',
    'container.build_id' => '4c467440',
    'container.build_time' => 1637092092,
], __DIR__.\DIRECTORY_SEPARATOR.'Container798Kc8x');
