<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLGQtxIw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLGQtxIw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLGQtxIw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLGQtxIw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLGQtxIw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LGQtxIw',
    'container.build_id' => 'e6726503',
    'container.build_time' => 1638190074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLGQtxIw');
